## **Operations on Dummy data**

In [ ]:
import pandas as pd

In [ ]:
Data={'Name':['Neha','Kavita','Priti','Ramesh','Suresh','Sushant','Ram','Raj','Sham','Radha'],
      'Age':[20,21,30,35,14,25,20,19,18,22],
      'Gender':['Female','Female','Female','Male','Male','Male','Male','Male','Male','Female'],
      'Salary':[40000,50000,60000,20000,122000,30000,56000,41000,20000,210000]
      }

In [ ]:
# 1. Created a Data Frame (df)
df1=pd.DataFrame(Data)
df1

      Name  Age  Gender  Salary
0     Neha   20  Female   40000
1   Kavita   21  Female   50000
2    Priti   30  Female   60000
3   Ramesh   35    Male   20000
4   Suresh   14    Male  122000
5  Sushant   25    Male   30000
6      Ram   20    Male   56000
7      Raj   19    Male   41000
8     Sham   18    Male   20000
9    Radha   22  Female  210000

In [ ]:
# 2. Find shape of the df
df1.shape

(10, 4)

In [ ]:
# 3. Find size of the df.
df1.size

40

In [ ]:
# 4. Find dimensions of the df
df1.ndim

2

In [ ]:
# 5. List all the columns in the df
df1.columns

Index(['Name', 'Age', 'Gender', 'Salary'], dtype='object')

In [ ]:
# 6.  Find datatype of each column in the df
df1.dtypes

Name      object
Age        int64
Gender    object
Salary     int64
dtype: object

In [ ]:
# 7.Find axes of the df.
df1.axes

[RangeIndex(start=0, stop=10, step=1),
 Index(['Name', 'Age', 'Gender', 'Salary'], dtype='object')]

In [ ]:
# 8. Find index of the df.
df1.index

RangeIndex(start=0, stop=10, step=1)

In [ ]:
# 9. Find all values of df
df1.values

array([['Neha', 20, 'Female', 40000],
       ['Kavita', 21, 'Female', 50000],
       ['Priti', 30, 'Female', 60000],
       ['Ramesh', 35, 'Male', 20000],
       ['Suresh', 14, 'Male', 122000],
       ['Sushant', 25, 'Male', 30000],
       ['Ram', 20, 'Male', 56000],
       ['Raj', 19, 'Male', 41000],
       ['Sham', 18, 'Male', 20000],
       ['Radha', 22, 'Female', 210000]], dtype=object)

In [ ]:
# 10. Check whether the df is empty.
df1.empty

False

In [ ]:
# 11.Transpose the df
df1.T

,0,1,2,3,4,5,6,7,8,9
Name,Neha,Kavita,Priti,Ramesh,Suresh,Sushant,Ram,Raj,Sham,Radha
Age,20,21,30,35,14,25,20,19,18,22
Gender,Female,Female,Female,Male,Male,Male,Male,Male,Male,Female
Salary,40000,50000,60000,20000,122000,30000,56000,41000,20000,210000

In [ ]:
# 12. Find detailed information about the df
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    10 non-null     object
 1   Age     10 non-null     int64
 2   Gender  10 non-null     object
 3   Salary  10 non-null     int64
dtypes: int64(2), object(2)
memory usage: 448.0+ bytes

In [ ]:
# 13. Display (first) top ‘n’ records from the df.
df1.head(3)

     Name  Age  Gender  Salary
0    Neha   20  Female   40000
1  Kavita   21  Female   50000
2   Priti   30  Female   60000

In [ ]:
 # 14. Display (last) bottom ‘n’ records from the df.
 df1.tail(3)

    Name  Age  Gender  Salary
7    Raj   19    Male   41000
8   Sham   18    Male   20000
9  Radha   22  Female  210000

In [ ]:
# 15. Display descriptive statistics for numerical columns from the df
df1.describe()

             Age         Salary
count  10.000000      10.000000
mean   22.400000   64900.000000
std     6.131884   58765.919829
min    14.000000   20000.000000
25%    19.250000   32500.000000
50%    20.500000   45500.000000
75%    24.250000   59000.000000
max    35.000000  210000.000000

In [ ]:
# 16. Find mean, median, mode, standard deviation values for numerical columns in df.
df1.describe().T

,count,mean,std,min,25%,50%,75%,max
Age,10.0,22.4,6.131884,14.0,19.25,20.5,24.25,35.0
Salary,10.0,64900.0,58765.919829,20000.0,32500.00,45500.0,59000.00,210000.0

In [ ]:
# 17. Return a random sample from df.
df1.sample(3)

    Name  Age  Gender  Salary
8   Sham   18    Male   20000
9  Radha   22  Female  210000
6    Ram   20    Male   56000

In [ ]:
# 18. Find the unique values for the categorical columns in the df.
df1['Gender'].unique()

array(['Female', 'Male'], dtype=object)

In [ ]:
# 19. Find the number of unique values for categorical columns in df.
df1['Gender'].nunique()

2

In [ ]:
# 20. Locate first row in the df using loc.
df1.loc[0]

Name        Neha
Age           20
Gender    Female
Salary     40000
Name: 0, dtype: object

In [ ]:
# 21. Locate nth row in the df using loc.
df1.loc[3]

Name      Ramesh
Age           35
Gender      Male
Salary     20000
Name: 3, dtype: object

In [ ]:
# 22.Locate last row in the df using loc
df1.loc[9]

Name       Radha
Age           22
Gender    Female
Salary    210000
Name: 9, dtype: object

In [ ]:
# 23. Locate all values in a range in df using loc
df1.loc[0:3]

     Name  Age  Gender  Salary
0    Neha   20  Female   40000
1  Kavita   21  Female   50000
2   Priti   30  Female   60000
3  Ramesh   35    Male   20000

In [ ]:
# 24. Locate all the rows in df with specific criteria using loc.
df1.loc[df1['Age']>20]

      Name  Age  Gender  Salary
1   Kavita   21  Female   50000
2    Priti   30  Female   60000
3   Ramesh   35    Male   20000
5  Sushant   25    Male   30000
9    Radha   22  Female  210000

In [ ]:
# 25. Locate all the rows in df with specific criteria with logical and operator using loc.
df1.loc[(df1['Age']>20) & (df1['Gender']=='Female')]

     Name  Age  Gender  Salary
1  Kavita   21  Female   50000
2   Priti   30  Female   60000
9   Radha   22  Female  210000

In [ ]:
# 26. Locate first row in the df using iloc.
df1.iloc[0]

Name        Neha
Age           20
Gender    Female
Salary     40000
Name: 0, dtype: object

In [ ]:
# 27. Locate nth row in the df using iloc.
df1.iloc[3]

Name      Ramesh
Age           35
Gender      Male
Salary     20000
Name: 3, dtype: object

In [ ]:
# 28. Locate last row in the df using iloc
df1.iloc[-1]

Name       Radha
Age           22
Gender    Female
Salary    210000
Name: 9, dtype: object

In [ ]:
# 29. Locate first, nth, last column in df using iloc.
df1.iloc[:,[0,3]]

      Name  Salary
0     Neha   40000
1   Kavita   50000
2    Priti   60000
3   Ramesh   20000
4   Suresh  122000
5  Sushant   30000
6      Ram   56000
7      Raj   41000
8     Sham   20000
9    Radha  210000

In [ ]:
# 30. Locate all the rows in df within a specific range of row index using iloc.
df1.iloc[0:3]

     Name  Age  Gender  Salary
0    Neha   20  Female   40000
1  Kavita   21  Female   50000
2   Priti   30  Female   60000

In [ ]:
# 31. Locate all columns within a range of column index using iloc.
df1.iloc[:,0:3]

      Name  Age  Gender
0     Neha   20  Female
1   Kavita   21  Female
2    Priti   30  Female
3   Ramesh   35    Male
4   Suresh   14    Male
5  Sushant   25    Male
6      Ram   20    Male
7      Raj   19    Male
8     Sham   18    Male
9    Radha   22  Female

In [ ]:
# 32. Locate Second through third rows and first 2 columns using iloc.
df1.iloc[1:3,0:2]

     Name  Age
1  Kavita   21
2   Priti   30

In [ ]:
# 33. Locate 1st and 6th rows and 1st and 4th columns using iloc.
df1.iloc[[0,5],[0,3]]

      Name  Salary
0     Neha   40000
5  Sushant   30000

## **operations on Titanic dataset**

In [ ]:
import pandas as pd

In [ ]:
# 1. Created a Data Frame (df)
df1 =pd.read_excel('Titanic-Dataset.xlsx')
df1

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
# 2. Find shape of the df1
df1.shape

(891, 12)

In [ ]:
# 3. Find size of the df1
df1.size

10692

In [ ]:
# 4. Find dimensions of the df1
df1.ndim

2

In [ ]:
# 5. List all the columns in the df1
df1.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [ ]:
# 6. Find datatype of each column in the df1
df1.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [ ]:
# 7. Find axes of the df1
df1.axes

[RangeIndex(start=0, stop=891, step=1),
 Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
        'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
       dtype='object')]

In [ ]:
# 8. Find index of the df1
df1.index

RangeIndex(start=0, stop=891, step=1)

In [ ]:
# 9. Find all values of df1
df1.values

array([[1, 0, 3, ..., 7.25, nan, 'S'],
       [2, 1, 1, ..., 71.2833, 'C85', 'C'],
       [3, 1, 3, ..., 7.925, nan, 'S'],
       ...,
       [889, 0, 3, ..., 23.45, nan, 'S'],
       [890, 1, 1, ..., 30.0, 'C148', 'C'],
       [891, 0, 3, ..., 7.75, nan, 'Q']], dtype=object)

In [ ]:
# 10. Check whether the df1 is empty
df1.empty

False

In [ ]:
# 11. Transpose the df1
df1.T

,0,1,2,3,4,5,6,7,8,9,...,881,882,883,884,885,886,887,888,889,890
PassengerId,1,2,3,4,5,6,7,8,9,10,...,882,883,884,885,886,887,888,889,890,891
Survived,0,1,1,1,0,0,0,0,1,1,...,0,0,0,0,0,0,1,0,1,0
Pclass,3,1,3,1,3,3,1,3,3,2,...,3,3,2,3,3,2,1,3,1,3
Name,"Braund, Mr. Owen Harris","Cumings, Mrs. John Bradley (Florence Briggs Th...","Heikkinen, Miss. Laina","Futrelle, Mrs. Jacques Heath (Lily May Peel)","Allen, Mr. William Henry","Moran, Mr. James","McCarthy, Mr. Timothy J","Palsson, Master. Gosta Leonard","Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)","Nasser, Mrs. Nicholas (Adele Achem)",...,"Markun, Mr. Johann","Dahlberg, Miss. Gerda Ulrika","Banfield, Mr. Frederick James","Sutehall, Mr. Henry Jr","Rice, Mrs. William (Margaret Norton)","Montvila, Rev. Juozas","Graham, Miss. Margaret Edith","Johnston, Miss. Catherine Helen ""Carrie""","Behr, Mr. Karl Howell","Dooley, Mr. Patrick"
Sex,male,female,female,female,male,male,male,male,female,female,...,male,female,male,male,female,male,female,female,male,male
Age,22.0,38.0,26.0,35.0,35.0,NaN,54.0,2.0,27.0,14.0,...,33.0,22.0,28.0,25.0,39.0,27.0,19.0,NaN,26.0,32.0
SibSp,1,1,0,1,0,0,0,3,0,1,...,0,0,0,0,0,0,0,1,0,0
Parch,0,0,0,0,0,0,0,1,2,0,...,0,0,0,0,5,0,0,2,0,0
Ticket,A/5 21171,PC 17599,STON/O2. 3101282,113803,373450,330877,17463,349909,347742,237736,...,349257,7552,C.A./SOTON 34068,SOTON/OQ 392076,382652,211536,112053,W./C. 6607,111369,370376
Fare,7.25,71.2833,7.925,53.1,8.05,8.4583,51.8625,21.075,11.1333,30.0708,...,7.8958,10.5167,10.5,7.05,29.125,13.0,30.0,23.45,30.0,7.75
Cabin,NaN,C85,NaN,C123,NaN,NaN,E46,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,B42,NaN,C148,NaN
Embarked,S,C,S,S,S,Q,S,S,S,C,...,S,S,S,S,Q,S,S,S,C,Q

In [ ]:
# 12. Find detailed information about the df1
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [ ]:
# 13. Display (first) top ‘n’ records from the df1
df1.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [ ]:
# 14. Display (last) bottom ‘n’ records from the df1
df1.tail(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [ ]:
# 15. Display descriptive statistics for numerical columns from the df1
df1.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [ ]:
# 16. Find mean, median, mode, standard deviation values for numerical columns in df1
df1.describe().T

,count,mean,std,min,25%,50%,75%,max
PassengerId,891.0,446.000000,257.353842,1.00,223.5000,446.0000,668.5,891.0000
Survived,891.0,0.383838,0.486592,0.00,0.0000,0.0000,1.0,1.0000
Pclass,891.0,2.308642,0.836071,1.00,2.0000,3.0000,3.0,3.0000
Age,714.0,29.699118,14.526497,0.42,20.1250,28.0000,38.0,80.0000
SibSp,891.0,0.523008,1.102743,0.00,0.0000,0.0000,1.0,8.0000
Parch,891.0,0.381594,0.806057,0.00,0.0000,0.0000,0.0,6.0000
Fare,891.0,32.204208,49.693429,0.00,7.9104,14.4542,31.0,512.3292

In [ ]:
# 17. Return a random sample from df1
df1.sample(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
562,563,0,2,"Norman, Mr. Robert Douglas",male,28.0,0,0,218629,13.5000,NaN,S
742,743,1,1,"Ryerson, Miss. Susan Parker ""Suzette""",female,21.0,2,2,PC 17608,262.3750,B57 B59 B63 B66,C
44,45,1,3,"Devaney, Miss. Margaret Delia",female,19.0,0,0,330958,7.8792,NaN,Q

In [ ]:
# 18. Find the unique values for the categorical columns in the df1
df1['Sex'].unique()

array(['male', 'female'], dtype=object)

In [ ]:
# 19. Find the number of unique values for categorical columns in df1
df1['Sex'].nunique()

2

In [ ]:
# 20. Locate first row in the df1 using loc.
df1.loc[0]

PassengerId                          1
Survived                             0
Pclass                               3
Name           Braund, Mr. Owen Harris
Sex                               male
Age                               22.0
SibSp                                1
Parch                                0
Ticket                       A/5 21171
Fare                              7.25
Cabin                              NaN
Embarked                             S
Name: 0, dtype: object

In [ ]:
# 21. Locate nth row in the df1 using loc.
df1.loc[3]

PassengerId                                               4
Survived                                                  1
Pclass                                                    1
Name           Futrelle, Mrs. Jacques Heath (Lily May Peel)
Sex                                                  female
Age                                                    35.0
SibSp                                                     1
Parch                                                     0
Ticket                                               113803
Fare                                                   53.1
Cabin                                                  C123
Embarked                                                  S
Name: 3, dtype: object

In [ ]:
# 22. Locate last row in the df1 using loc.
df1.loc[886]

PassengerId                      887
Survived                           0
Pclass                             2
Name           Montvila, Rev. Juozas
Sex                             male
Age                             27.0
SibSp                              0
Parch                              0
Ticket                        211536
Fare                            13.0
Cabin                            NaN
Embarked                           S
Name: 886, dtype: object

In [ ]:
# 23. Locate all values in a range in df1 using loc.
df1.loc[0:3]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S

In [ ]:
# 24. Locate all the rows in df1 with specific criteria using loc.
df1.loc[df1['Sex']=='male']

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
# 25. Locate all the rows in df1 with specific criteria with logical and operator using loc.
df1.loc[(df1['Sex']=='male') & (df1['Survived']==1)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
21,22,1,2,"Beesley, Mr. Lawrence",male,34.0,0,0,248698,13.0000,D56,S
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S
36,37,1,3,"Mamee, Mr. Hanna",male,NaN,0,0,2677,7.2292,NaN,C
55,56,1,1,"Woolner, Mr. Hugh",male,NaN,0,0,19947,35.5000,C52,S
...,...,...,...,...,...,...,...,...,...,...,...,...
838,839,1,3,"Chip, Mr. Chang",male,32.0,0,0,1601,56.4958,NaN,S
839,840,1,1,"Marechal, Mr. Pierre",male,NaN,0,0,11774,29.7000,C47,C
857,858,1,1,"Daly, Mr. Peter Denis",male,51.0,0,0,113055,26.5500,E17,S
869,870,1,3,"Johnson, Master. Harold Theodor",male,4.0,1,1,347742,11.1333,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

In [ ]:
# 26. Locate first row in the df1 using iloc.
df1.iloc[0]

PassengerId                          1
Survived                             0
Pclass                               3
Name           Braund, Mr. Owen Harris
Sex                               male
Age                               22.0
SibSp                                1
Parch                                0
Ticket                       A/5 21171
Fare                              7.25
Cabin                              NaN
Embarked                             S
Name: 0, dtype: object

In [ ]:
# 27. Locate nth row in the df1 using iloc.
df1.iloc[3]

PassengerId                                               4
Survived                                                  1
Pclass                                                    1
Name           Futrelle, Mrs. Jacques Heath (Lily May Peel)
Sex                                                  female
Age                                                    35.0
SibSp                                                     1
Parch                                                     0
Ticket                                               113803
Fare                                                   53.1
Cabin                                                  C123
Embarked                                                  S
Name: 3, dtype: object

In [ ]:
# 28. Locate last row in the df1 using iloc.
df1.iloc[-1]

PassengerId                    891
Survived                         0
Pclass                           3
Name           Dooley, Mr. Patrick
Sex                           male
Age                           32.0
SibSp                            0
Parch                            0
Ticket                      370376
Fare                          7.75
Cabin                          NaN
Embarked                         Q
Name: 890, dtype: object

In [ ]:
# 29. Locate first, nth, last column in df1 using iloc.
df1.iloc[:,[0,3]]

     PassengerId                                               Name
0              1                            Braund, Mr. Owen Harris
1              2  Cumings, Mrs. John Bradley (Florence Briggs Th...
2              3                             Heikkinen, Miss. Laina
3              4       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4              5                           Allen, Mr. William Henry
..           ...                                                ...
886          887                              Montvila, Rev. Juozas
887          888                       Graham, Miss. Margaret Edith
888          889           Johnston, Miss. Catherine Helen "Carrie"
889          890                              Behr, Mr. Karl Howell
890          891                                Dooley, Mr. Patrick

[891 rows x 2 columns]

In [ ]:
# 30. Locate all the rows in df1 within a specific range of row index using iloc.
df1.iloc[0:3]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [ ]:
# 31. Locate all columns within a range of column index using iloc.
df1.iloc[:,0:3]

     PassengerId  Survived  Pclass
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

[891 rows x 3 columns]

In [ ]:
# 32. Locate Second through third rows and first 2 columns using iloc.
df1.iloc[1:3,0:2]

   PassengerId  Survived
1            2         1
2            3         1

In [ ]:
# 33. Locate 1st and 6th rows and 1st and 4th columns using iloc.
df1.iloc[[0,5],[0,3]]

   PassengerId                     Name
0            1  Braund, Mr. Owen Harris
5            6         Moran, Mr. James