In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_excel('WDICountry.xlsx')
df.tail(100)

,Country Code,Short Name,Table Name,Long Name,2-alpha code,Currency Unit,Region,Income Group,WB-2 code,National accounts base year,...,System of trade,Government Accounting concept,IMF data dissemination standard,Latest population census,Latest household survey,Source of most recent Income and expenditure data,Vital registration complete,Latest agricultural census,Latest industrial data,Latest trade data
167,MWI,Malawi,Malawi,Republic of Malawi,MW,Malawi kwacha,Sub-Saharan Africa,Low income,MW,2017,...,General trade system,Budgetary central government,Enhanced General Data Dissemination System (e-...,2018,Fifth Integrated Household Survey 2019-2020; M...,"Integrated household survey (IHS), 2016",NaN,2006-2007,2012.0,2017.0
168,MYS,Malaysia,Malaysia,Malaysia,MY,Malaysian ringgit,East Asia & Pacific,Upper middle income,MY,2015,...,General trade system,Budgetary central government,Special Data Dissemination Standard (SDDS),2020 (expected),"World Health Survey, 2003","Income survey (IS), 2015",Yes,"2015. Economic Census, Natural Resources Censu...",2012.0,2018.0
169,NAC,North America,North America,North America,XU,NaN,NaN,NaN,XU,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
170,NAM,Namibia,Namibia,Republic of Namibia,NaN,Namibian dollar,Sub-Saharan Africa,Upper middle income,NaN,2015,...,General trade system,Budgetary central government,Enhanced General Data Dissemination System (e-...,2011,"Demographic and Health Survey, 2013","Expenditure survey/budget survey (ES/BS), 2015",NaN,2013-2014,2013.0,2018.0
171,NCL,New Caledonia,New Caledonia,New Caledonia,NC,CFP franc,East Asia & Pacific,High income,NC,2017,...,General trade system,NaN,NaN,2019,NaN,NaN,Yes,NaN,NaN,2015.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
262,ZAF,South Africa,South Africa,Republic of South Africa,ZA,South African rand,Sub-Saharan Africa,Upper middle income,ZA,2015,...,General trade system,Consolidated central government,Special Data Dissemination Standard (SDDS),2011,"Demographic and Health Survey, 2016","Expenditure survey/budget survey (ES/BS), 2014/15",NaN,2007,2010.0,2018.0
263,ZMB,Zambia,Zambia,Republic of Zambia,ZM,New Zambian kwacha,Sub-Saharan Africa,Lower middle income,ZM,2010,...,General trade system,Budgetary central government,Enhanced General Data Dissemination System (e-...,2020 (expected),"Demographic and Health Survey, 2018","Integrated household survey (IHS), 2015",NaN,NaN,1994.0,2018.0
264,ZWE,Zimbabwe,Zimbabwe,Republic of Zimbabwe,ZW,Zimbabwean Dollar,Sub-Saharan Africa,Lower middle income,ZW,2019,...,General trade system,Budgetary central government,Enhanced General Data Dissemination System (e-...,2012,"Multiple Indicator Cluster Survey, 2019","Integrated household survey (IHS), 2011/12",NaN,NaN,NaN,2018.0
265,AUS,Australia,Australia,Commonwealth of Australia,AU,Australian dollar,East Asia & Pacific,High income,AU,Original chained constant price data are resca...,...,General trade system,Consolidated central government,Special Data Dissemination Standard (SDDS),2016,NaN,"Expenditure survey/budget survey (ES/BS), 2010",Yes,2015-2016,2013.0,2018.0
266,VEN,Venezuela,"Venezuela, RB",Rep√∫blica Bolivariana de Venezuela,VE,Venezuelan bolivar fuerte,Latin America & Caribbean,NaN,VE,1997,...,NaN,NaN,Enhanced General Data Dissemination System (e-...,2011,"Multiple Indicator Cluster Survey, 2000","Integrated household survey (IHS), 2015",NaN,2008,1998.0,2013.0

In [3]:
# identify null values
df.isnull().sum()

Country Code                                           0
Short Name                                             0
Table Name                                             0
Long Name                                              0
2-alpha code                                           2
Currency Unit                                         48
Region                                                48
Income Group                                          50
WB-2 code                                              1
National accounts base year                           56
National accounts reference year                     192
SNA price valuation                                   58
Lending category                                     122
Other groups                                         208
System of National Accounts                           57
Alternative conversion factor                        267
PPP survey year                                      267
Balance of Payments Manual in use                     70
External debt Reporting status                       146
System of trade                                       94
Government Accounting concept                        108
IMF data dissemination standard                       77
Latest population census                              51
Latest household survey                              112
Source of most recent Income and expenditure data     97
Vital registration complete                          146
Latest agricultural census                           137
Latest industrial data                               118
Latest trade data                                     74
dtype: int64

In [4]:
df.isnull().sum().sum()

2606

In [5]:
df.isna().sum()

Country Code                                           0
Short Name                                             0
Table Name                                             0
Long Name                                              0
2-alpha code                                           2
Currency Unit                                         48
Region                                                48
Income Group                                          50
WB-2 code                                              1
National accounts base year                           56
National accounts reference year                     192
SNA price valuation                                   58
Lending category                                     122
Other groups                                         208
System of National Accounts                           57
Alternative conversion factor                        267
PPP survey year                                      267
Balance of Payments Manual in use                     70
External debt Reporting status                       146
System of trade                                       94
Government Accounting concept                        108
IMF data dissemination standard                       77
Latest population census                              51
Latest household survey                              112
Source of most recent Income and expenditure data     97
Vital registration complete                          146
Latest agricultural census                           137
Latest industrial data                               118
Latest trade data                                     74
dtype: int64

In [6]:
df.isna().sum().sum()

2606

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 267 entries, 0 to 266
Data columns (total 29 columns):
 #   Column                                             Non-Null Count  Dtype
---  ------                                             --------------  -----
 0   Country Code                                       267 non-null    object
 1   Short Name                                         267 non-null    object
 2   Table Name                                         267 non-null    object
 3   Long Name                                          267 non-null    object
 4   2-alpha code                                       265 non-null    object
 5   Currency Unit                                      219 non-null    object
 6   Region                                             219 non-null    object
 7   Income Group                                       217 non-null    object
 8   WB-2 code                                          266 non-null    object
 9   National accounts base year                        211 non-null    object
 10  National accounts reference year                   75 non-null     float64
 11  SNA price valuation                                209 non-null    object
 12  Lending category                                   145 non-null    object
 13  Other groups                                       59 non-null     object
 14  System of National Accounts                        210 non-null    object
 15  Alternative conversion factor                      0 non-null      float64
 16  PPP survey year                                    0 non-null      float64
 17  Balance of Payments Manual in use                  197 non-null    object
 18  External debt Reporting status                     121 non-null    object
 19  System of trade                                    173 non-null    object
 20  Government Accounting concept                      159 non-null    object
 21  IMF data dissemination standard                    190 non-null    object
 22  Latest population census                           216 non-null    object
 23  Latest household survey                            155 non-null    object
 24  Source of most recent Income and expenditure data  170 non-null    object
 25  Vital registration complete                        121 non-null    object
 26  Latest agricultural census                         130 non-null    object
 27  Latest industrial data                             149 non-null    float64
 28  Latest trade data                                  193 non-null    float64
dtypes: float64(5), object(24)
memory usage: 60.6+ KB

## 1.3 Perform appropriate imputations to handle the missing values.

In [8]:
# column 2-alpha code
df['2-alpha code'].unique()

array(['AW', 'ZH', 'AF', 'ZI', 'AO', 'AL', 'AD', '1A', 'AE', 'AR', 'AM',
       'AS', 'AG', 'AU', 'AT', 'AZ', 'BI', 'BE', 'BJ', 'BF', 'BD', 'BG',
       'BH', 'BS', 'BA', 'BY', 'BZ', 'BM', 'BO', 'BR', 'BB', 'BN', 'BT',
       'BW', 'CF', 'CA', 'B8', 'CH', nan, 'CL', 'CN', 'CI', 'CM', 'CD',
       'CG', 'CO', 'KM', 'CV', 'CR', 'S3', 'CU', 'CW', 'KY', 'CY', 'CZ',
       'DE', 'DJ', 'DM', 'DK', 'DO', 'DZ', '4E', 'V2', 'Z4', '7E', 'Z7',
       'EC', 'EG', 'XC', 'ER', 'ES', 'EE', 'ET', 'EU', 'F1', 'FI', 'FJ',
       'FR', 'FO', 'FM', 'GA', 'GB', 'GE', 'GH', 'GI', 'GN', 'GM', 'GW',
       'GQ', 'GR', 'GD', 'GL', 'GT', 'GU', 'GY', 'XD', 'HK', 'HN', 'XE',
       'HR', 'HT', 'HU', 'XF', 'ZT', 'XG', 'XH', 'ID', 'XI', 'IM', 'IN',
       'IE', 'IR', 'IQ', 'IS', 'IL', 'IT', 'JM', 'JO', 'JP', 'KZ', 'KE',
       'KG', 'KH', 'KI', 'KN', 'KR', 'KW', 'XJ', 'LA', 'LB', 'LR', 'LY',
       'LC', 'ZJ', 'XL', 'XM', 'LI', 'LK', 'XN', 'XO', 'LS', 'V3', 'LT',
       'LU', 'LV', 'MO', 'MF', 'MA', 'MC', 'MD', 'MG', 'MV', 'ZQ', 'MX',
       'MH', 'XP', 'MK', 'ML', 'MT', 'MM', 'XQ', 'ME', 'MN', 'MP', 'MZ',
       'MR', 'MU', 'MW', 'MY', 'XU', 'NC', 'NE', 'NG', 'NI', 'NL', 'NO',
       'NP', 'NR', 'NZ', 'OE', 'OM', 'S4', 'PK', 'PA', 'PE', 'PH', 'PW',
       'PG', 'PL', 'V1', 'PR', 'KP', 'PT', 'PY', 'PS', 'S2', 'V4', 'PF',
       'QA', 'RO', 'RU', 'RW', '8S', 'SA', 'SD', 'SN', 'SG', 'SB', 'SL',
       'SV', 'SM', 'SO', 'RS', 'ZF', 'SS', 'ZG', 'S1', 'ST', 'SR', 'SK',
       'SI', 'SE', 'SZ', 'SX', 'SC', 'SY', 'TC', 'TD', 'T4', 'T7', 'TG',
       'TH', 'TJ', 'TM', 'T2', 'TL', 'T3', 'TO', 'T5', 'T6', 'TT', 'TN',
       'TR', 'TV', 'TZ', 'UG', 'UA', 'XT', 'UY', 'US', 'UZ', 'VC', 'VE',
       'VG', 'VI', 'VN', 'VU', '1W', 'WS', 'XK', 'YE', 'ZA', 'ZM', 'ZW'],
      dtype=object)

In [9]:
missing_rows = df[df['2-alpha code'].isnull()]
missing_rows

,Country Code,Short Name,Table Name,Long Name,2-alpha code,Currency Unit,Region,Income Group,WB-2 code,National accounts base year,...,System of trade,Government Accounting concept,IMF data dissemination standard,Latest population census,Latest household survey,Source of most recent Income and expenditure data,Vital registration complete,Latest agricultural census,Latest industrial data,Latest trade data
38,CHI,Channel Islands,Channel Islands,Channel Islands,NaN,Pound sterling,Europe & Central Asia,High income,JG,NaN,...,NaN,NaN,NaN,Guernsey: 2015; Jersey: 2011.,NaN,NaN,Yes. Vital registration for Guernsey and Jersey.,NaN,NaN,NaN
170,NAM,Namibia,Namibia,Republic of Namibia,NaN,Namibian dollar,Sub-Saharan Africa,Upper middle income,NaN,2015,...,General trade system,Budgetary central government,Enhanced General Data Dissemination System (e-...,2011,"Demographic and Health Survey, 2013","Expenditure survey/budget survey (ES/BS), 2015",NaN,2013-2014,2013.0,2018.0

In [10]:
missing_rows = df[df['Currency Unit'].isnull()]
missing_rows

,Country Code,Short Name,Table Name,Long Name,2-alpha code,Currency Unit,Region,Income Group,WB-2 code,National accounts base year,...,System of trade,Government Accounting concept,IMF data dissemination standard,Latest population census,Latest household survey,Source of most recent Income and expenditure data,Vital registration complete,Latest agricultural census,Latest industrial data,Latest trade data
1,AFE,Africa Eastern and Southern,Africa Eastern and Southern,Africa Eastern and Southern,ZH,NaN,NaN,NaN,ZH,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AFW,Africa Western and Central,Africa Western and Central,Africa Western and Central,ZI,NaN,NaN,NaN,ZI,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,ARB,Arab World,Arab World,Arab World,1A,NaN,NaN,NaN,1A,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,CEB,Central Europe and the Baltics,Central Europe and the Baltics,Central Europe and the Baltics,B8,NaN,NaN,NaN,B8,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,CSS,Caribbean small states,Caribbean small states,Caribbean small states,S3,NaN,NaN,NaN,S3,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61,EAP,East Asia & Pacific (excluding high income),East Asia & Pacific (excluding high income),East Asia & Pacific (excluding high income),4E,NaN,NaN,NaN,4E,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,EAR,Early-demographic dividend,Early-demographic dividend,Early-demographic dividend,V2,NaN,NaN,NaN,V2,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,EAS,East Asia & Pacific,East Asia & Pacific,East Asia & Pacific,Z4,NaN,NaN,NaN,Z4,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64,ECA,Europe & Central Asia (excluding high income),Europe & Central Asia (excluding high income),Europe & Central Asia (excluding high income),7E,NaN,NaN,NaN,7E,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65,ECS,Europe & Central Asia,Europe & Central Asia,Europe & Central Asia,Z7,NaN,NaN,NaN,Z7,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68,EMU,Euro area,Euro area,Euro area,XC,NaN,NaN,NaN,XC,NaN,...,NaN,NaN,Special Data Dissemination Standard (SDDS),NaN,NaN,NaN,NaN,NaN,NaN,NaN
73,EUU,European Union,European Union,European Union,EU,NaN,NaN,NaN,EU,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
74,FCS,Fragile and conflict affected situations,Fragile and conflict affected situations,Fragile and conflict affected situations,F1,NaN,NaN,NaN,F1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95,HIC,High income,High income,High income,XD,NaN,NaN,NaN,XD,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,HPC,Heavily indebted poor countries (HIPC),Heavily indebted poor countries (HIPC),Heavily indebted poor countries (HIPC),XE,NaN,NaN,NaN,XE,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
102,IBD,IBRD only,IBRD only,IBRD only,XF,NaN,NaN,NaN,XF,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
103,IBT,IDA & IBRD total,IDA & IBRD total,IDA & IBRD total,ZT,NaN,NaN,NaN,ZT,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
104,IDA,IDA total,IDA total,IDA total,XG,NaN,NaN,NaN,XG,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
105,IDB,IDA blend,IDA blend,IDA blend,XH,NaN,NaN,NaN,XH,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
107,IDX,IDA only,IDA only,IDA only,XI,NaN,NaN,NaN,XI,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
127,LAC,Latin America & Caribbean (excluding high income),Latin America & Caribbean (excluding high income),Latin America & Caribbean (excluding high income),XJ,NaN,NaN,NaN,XJ,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
133,LCN,Latin America & Caribbean,Latin America & Caribbean,Latin America & Caribbean,ZJ,NaN,NaN,NaN,ZJ,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
134,LDC,Least developed countries: UN classification,Least developed countries: UN classification,Least developed countries: UN classification,XL,NaN,NaN,NaN,XL,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
135,LIC,Low income,Low income,Low income,XM,NaN,NaN,NaN,XM,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
138,LMC,Lower middle income,Lower middle income,Lower middle income,XN,NaN,NaN,NaN,XN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
139,LMY,Low & middle income,Low & middle income,Low & middle income,XO,NaN,NaN,NaN,XO,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
141,LTE,Late-demographic dividend,Late-demographic dividend,Late-demographic dividend,V3,NaN,NaN,NaN,V3,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
152,MEA,Middle East & North Africa,Middle East & North Africa,Middle East & North Africa,ZQ,NaN,NaN,NaN,ZQ,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
155,MIC,Middle income,Middle income,Middle income,XP,NaN,NaN,NaN,XP,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
160,MNA,Middle East & North Africa (excluding high inc...,Middle East & North Africa (excluding high inc...,Middle East & North Africa (excluding high inc...,XQ,NaN,NaN,NaN,XQ,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
169,NAC,North America,North America,North America,XU,NaN,NaN,NaN,XU,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
180,OED,OECD members,OECD members,OECD members,OE,NaN,NaN,NaN,OE,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
182,OSS,Other small states,Other small states,Other small states,S4,NaN,NaN,NaN,S4,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
190,PRE,Pre-demographic dividend,Pre-demographic dividend,Pre-demographic dividend,V1,NaN,NaN,NaN,V1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
196,PSS,Pacific island small states,Pacific island small states,Pacific island small states,S2,NaN,NaN,NaN,S2,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
197,PST,Post-demographic dividend,Post-demographic dividend,Post-demographic dividend,V4,NaN,NaN,NaN,V4,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
203,SAS,South Asia,South Asia,South Asia,8S,NaN,NaN,NaN,8S,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
214,SSA,Sub-Saharan Africa (excluding high income),Sub-Saharan Africa (excluding high income),Sub-Saharan Africa (excluding high income),ZF,NaN,NaN,NaN,ZF,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
216,SSF,Sub-Saharan Africa,Sub-Saharan Africa,Sub-Saharan Africa,ZG,NaN,NaN,NaN,ZG,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
217,SST,Small states,Small states,Small states,S1,NaN,NaN,NaN,S1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
229,TEA,East Asia & Pacific (IDA & IBRD),East Asia & Pacific (IDA & IBRD),East Asia & Pacific (IDA & IBRD),T4,NaN,NaN,NaN,T4,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
230,TEC,Europe & Central Asia (IDA & IBRD),Europe & Central Asia (IDA & IBRD),Europe & Central Asia (IDA & IBRD),T7,NaN,NaN,NaN,T7,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
235,TLA,Latin America & Caribbean (IDA & IBRD),Latin America & Caribbean (IDA & IBRD),Latin America & Caribbean (IDA & IBRD),T2,NaN,NaN,NaN,T2,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
237,TMN,Middle East & North Africa (IDA & IBRD),Middle East & North Africa (IDA & IBRD),Middle East & North Africa (IDA & IBRD),T3,NaN,NaN,NaN,T3,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
239,TSA,South Asia (IDA & IBRD),South Asia (IDA & IBRD),South Asia (IDA & IBRD),T5,NaN,NaN,NaN,T5,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
240,TSS,Sub-Saharan Africa (IDA & IBRD),Sub-Saharan Africa (IDA & IBRD),Sub-Saharan Africa (IDA & IBRD),T6,NaN,NaN,NaN,T6,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
248,UMC,Upper middle income,Upper middle income,Upper middle income,XT,NaN,NaN,NaN,XT,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
258,WLD,World,World,World,1W,NaN,NaN,NaN,1W,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
missing_rows = df[df['Region'].isnull()]
missing_rows

,Country Code,Short Name,Table Name,Long Name,2-alpha code,Currency Unit,Region,Income Group,WB-2 code,National accounts base year,...,System of trade,Government Accounting concept,IMF data dissemination standard,Latest population census,Latest household survey,Source of most recent Income and expenditure data,Vital registration complete,Latest agricultural census,Latest industrial data,Latest trade data
1,AFE,Africa Eastern and Southern,Africa Eastern and Southern,Africa Eastern and Southern,ZH,NaN,NaN,NaN,ZH,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AFW,Africa Western and Central,Africa Western and Central,Africa Western and Central,ZI,NaN,NaN,NaN,ZI,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,ARB,Arab World,Arab World,Arab World,1A,NaN,NaN,NaN,1A,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,CEB,Central Europe and the Baltics,Central Europe and the Baltics,Central Europe and the Baltics,B8,NaN,NaN,NaN,B8,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,CSS,Caribbean small states,Caribbean small states,Caribbean small states,S3,NaN,NaN,NaN,S3,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61,EAP,East Asia & Pacific (excluding high income),East Asia & Pacific (excluding high income),East Asia & Pacific (excluding high income),4E,NaN,NaN,NaN,4E,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,EAR,Early-demographic dividend,Early-demographic dividend,Early-demographic dividend,V2,NaN,NaN,NaN,V2,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,EAS,East Asia & Pacific,East Asia & Pacific,East Asia & Pacific,Z4,NaN,NaN,NaN,Z4,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64,ECA,Europe & Central Asia (excluding high income),Europe & Central Asia (excluding high income),Europe & Central Asia (excluding high income),7E,NaN,NaN,NaN,7E,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65,ECS,Europe & Central Asia,Europe & Central Asia,Europe & Central Asia,Z7,NaN,NaN,NaN,Z7,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68,EMU,Euro area,Euro area,Euro area,XC,NaN,NaN,NaN,XC,NaN,...,NaN,NaN,Special Data Dissemination Standard (SDDS),NaN,NaN,NaN,NaN,NaN,NaN,NaN
73,EUU,European Union,European Union,European Union,EU,NaN,NaN,NaN,EU,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
74,FCS,Fragile and conflict affected situations,Fragile and conflict affected situations,Fragile and conflict affected situations,F1,NaN,NaN,NaN,F1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95,HIC,High income,High income,High income,XD,NaN,NaN,NaN,XD,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,HPC,Heavily indebted poor countries (HIPC),Heavily indebted poor countries (HIPC),Heavily indebted poor countries (HIPC),XE,NaN,NaN,NaN,XE,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
102,IBD,IBRD only,IBRD only,IBRD only,XF,NaN,NaN,NaN,XF,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
103,IBT,IDA & IBRD total,IDA & IBRD total,IDA & IBRD total,ZT,NaN,NaN,NaN,ZT,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
104,IDA,IDA total,IDA total,IDA total,XG,NaN,NaN,NaN,XG,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
105,IDB,IDA blend,IDA blend,IDA blend,XH,NaN,NaN,NaN,XH,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
107,IDX,IDA only,IDA only,IDA only,XI,NaN,NaN,NaN,XI,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
127,LAC,Latin America & Caribbean (excluding high income),Latin America & Caribbean (excluding high income),Latin America & Caribbean (excluding high income),XJ,NaN,NaN,NaN,XJ,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
133,LCN,Latin America & Caribbean,Latin America & Caribbean,Latin America & Caribbean,ZJ,NaN,NaN,NaN,ZJ,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
134,LDC,Least developed countries: UN classification,Least developed countries: UN classification,Least developed countries: UN classification,XL,NaN,NaN,NaN,XL,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
135,LIC,Low income,Low income,Low income,XM,NaN,NaN,NaN,XM,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
138,LMC,Lower middle income,Lower middle income,Lower middle income,XN,NaN,NaN,NaN,XN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
139,LMY,Low & middle income,Low & middle income,Low & middle income,XO,NaN,NaN,NaN,XO,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
141,LTE,Late-demographic dividend,Late-demographic dividend,Late-demographic dividend,V3,NaN,NaN,NaN,V3,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
152,MEA,Middle East & North Africa,Middle East & North Africa,Middle East & North Africa,ZQ,NaN,NaN,NaN,ZQ,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
155,MIC,Middle income,Middle income,Middle income,XP,NaN,NaN,NaN,XP,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
160,MNA,Middle East & North Africa (excluding high inc...,Middle East & North Africa (excluding high inc...,Middle East & North Africa (excluding high inc...,XQ,NaN,NaN,NaN,XQ,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
169,NAC,North America,North America,North America,XU,NaN,NaN,NaN,XU,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
180,OED,OECD members,OECD members,OECD members,OE,NaN,NaN,NaN,OE,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
182,OSS,Other small states,Other small states,Other small states,S4,NaN,NaN,NaN,S4,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
190,PRE,Pre-demographic dividend,Pre-demographic dividend,Pre-demographic dividend,V1,NaN,NaN,NaN,V1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
196,PSS,Pacific island small states,Pacific island small states,Pacific island small states,S2,NaN,NaN,NaN,S2,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
197,PST,Post-demographic dividend,Post-demographic dividend,Post-demographic dividend,V4,NaN,NaN,NaN,V4,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
203,SAS,South Asia,South Asia,South Asia,8S,NaN,NaN,NaN,8S,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
214,SSA,Sub-Saharan Africa (excluding high income),Sub-Saharan Africa (excluding high income),Sub-Saharan Africa (excluding high income),ZF,NaN,NaN,NaN,ZF,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
216,SSF,Sub-Saharan Africa,Sub-Saharan Africa,Sub-Saharan Africa,ZG,NaN,NaN,NaN,ZG,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
217,SST,Small states,Small states,Small states,S1,NaN,NaN,NaN,S1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
229,TEA,East Asia & Pacific (IDA & IBRD),East Asia & Pacific (IDA & IBRD),East Asia & Pacific (IDA & IBRD),T4,NaN,NaN,NaN,T4,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
230,TEC,Europe & Central Asia (IDA & IBRD),Europe & Central Asia (IDA & IBRD),Europe & Central Asia (IDA & IBRD),T7,NaN,NaN,NaN,T7,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
235,TLA,Latin America & Caribbean (IDA & IBRD),Latin America & Caribbean (IDA & IBRD),Latin America & Caribbean (IDA & IBRD),T2,NaN,NaN,NaN,T2,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
237,TMN,Middle East & North Africa (IDA & IBRD),Middle East & North Africa (IDA & IBRD),Middle East & North Africa (IDA & IBRD),T3,NaN,NaN,NaN,T3,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
239,TSA,South Asia (IDA & IBRD),South Asia (IDA & IBRD),South Asia (IDA & IBRD),T5,NaN,NaN,NaN,T5,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
240,TSS,Sub-Saharan Africa (IDA & IBRD),Sub-Saharan Africa (IDA & IBRD),Sub-Saharan Africa (IDA & IBRD),T6,NaN,NaN,NaN,T6,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
248,UMC,Upper middle income,Upper middle income,Upper middle income,XT,NaN,NaN,NaN,XT,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
258,WLD,World,World,World,1W,NaN,NaN,NaN,1W,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
missing_rows = df[df['Income Group'].isnull()]
missing_rows

,Country Code,Short Name,Table Name,Long Name,2-alpha code,Currency Unit,Region,Income Group,WB-2 code,National accounts base year,...,System of trade,Government Accounting concept,IMF data dissemination standard,Latest population census,Latest household survey,Source of most recent Income and expenditure data,Vital registration complete,Latest agricultural census,Latest industrial data,Latest trade data
1,AFE,Africa Eastern and Southern,Africa Eastern and Southern,Africa Eastern and Southern,ZH,NaN,NaN,NaN,ZH,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AFW,Africa Western and Central,Africa Western and Central,Africa Western and Central,ZI,NaN,NaN,NaN,ZI,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,ARB,Arab World,Arab World,Arab World,1A,NaN,NaN,NaN,1A,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,CEB,Central Europe and the Baltics,Central Europe and the Baltics,Central Europe and the Baltics,B8,NaN,NaN,NaN,B8,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,CSS,Caribbean small states,Caribbean small states,Caribbean small states,S3,NaN,NaN,NaN,S3,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61,EAP,East Asia & Pacific (excluding high income),East Asia & Pacific (excluding high income),East Asia & Pacific (excluding high income),4E,NaN,NaN,NaN,4E,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,EAR,Early-demographic dividend,Early-demographic dividend,Early-demographic dividend,V2,NaN,NaN,NaN,V2,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,EAS,East Asia & Pacific,East Asia & Pacific,East Asia & Pacific,Z4,NaN,NaN,NaN,Z4,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64,ECA,Europe & Central Asia (excluding high income),Europe & Central Asia (excluding high income),Europe & Central Asia (excluding high income),7E,NaN,NaN,NaN,7E,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65,ECS,Europe & Central Asia,Europe & Central Asia,Europe & Central Asia,Z7,NaN,NaN,NaN,Z7,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68,EMU,Euro area,Euro area,Euro area,XC,NaN,NaN,NaN,XC,NaN,...,NaN,NaN,Special Data Dissemination Standard (SDDS),NaN,NaN,NaN,NaN,NaN,NaN,NaN
73,EUU,European Union,European Union,European Union,EU,NaN,NaN,NaN,EU,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
74,FCS,Fragile and conflict affected situations,Fragile and conflict affected situations,Fragile and conflict affected situations,F1,NaN,NaN,NaN,F1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95,HIC,High income,High income,High income,XD,NaN,NaN,NaN,XD,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,HPC,Heavily indebted poor countries (HIPC),Heavily indebted poor countries (HIPC),Heavily indebted poor countries (HIPC),XE,NaN,NaN,NaN,XE,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
102,IBD,IBRD only,IBRD only,IBRD only,XF,NaN,NaN,NaN,XF,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
103,IBT,IDA & IBRD total,IDA & IBRD total,IDA & IBRD total,ZT,NaN,NaN,NaN,ZT,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
104,IDA,IDA total,IDA total,IDA total,XG,NaN,NaN,NaN,XG,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
105,IDB,IDA blend,IDA blend,IDA blend,XH,NaN,NaN,NaN,XH,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
107,IDX,IDA only,IDA only,IDA only,XI,NaN,NaN,NaN,XI,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
127,LAC,Latin America & Caribbean (excluding high income),Latin America & Caribbean (excluding high income),Latin America & Caribbean (excluding high income),XJ,NaN,NaN,NaN,XJ,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
133,LCN,Latin America & Caribbean,Latin America & Caribbean,Latin America & Caribbean,ZJ,NaN,NaN,NaN,ZJ,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
134,LDC,Least developed countries: UN classification,Least developed countries: UN classification,Least developed countries: UN classification,XL,NaN,NaN,NaN,XL,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
135,LIC,Low income,Low income,Low income,XM,NaN,NaN,NaN,XM,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
138,LMC,Lower middle income,Lower middle income,Lower middle income,XN,NaN,NaN,NaN,XN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
139,LMY,Low & middle income,Low & middle income,Low & middle income,XO,NaN,NaN,NaN,XO,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
141,LTE,Late-demographic dividend,Late-demographic dividend,Late-demographic dividend,V3,NaN,NaN,NaN,V3,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
152,MEA,Middle East & North Africa,Middle East & North Africa,Middle East & North Africa,ZQ,NaN,NaN,NaN,ZQ,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
155,MIC,Middle income,Middle income,Middle income,XP,NaN,NaN,NaN,XP,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
160,MNA,Middle East & North Africa (excluding high inc...,Middle East & North Africa (excluding high inc...,Middle East & North Africa (excluding high inc...,XQ,NaN,NaN,NaN,XQ,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
169,NAC,North America,North America,North America,XU,NaN,NaN,NaN,XU,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
180,OED,OECD members,OECD members,OECD members,OE,NaN,NaN,NaN,OE,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
182,OSS,Other small states,Other small states,Other small states,S4,NaN,NaN,NaN,S4,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
190,PRE,Pre-demographic dividend,Pre-demographic dividend,Pre-demographic dividend,V1,NaN,NaN,NaN,V1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
196,PSS,Pacific island small states,Pacific island small states,Pacific island small states,S2,NaN,NaN,NaN,S2,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
197,PST,Post-demographic dividend,Post-demographic dividend,Post-demographic dividend,V4,NaN,NaN,NaN,V4,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
203,SAS,South Asia,South Asia,South Asia,8S,NaN,NaN,NaN,8S,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
214,SSA,Sub-Saharan Africa (excluding high income),Sub-Saharan Africa (excluding high income),Sub-Saharan Africa (excluding high income),ZF,NaN,NaN,NaN,ZF,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
216,SSF,Sub-Saharan Africa,Sub-Saharan Africa,Sub-Saharan Africa,ZG,NaN,NaN,NaN,ZG,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
217,SST,Small states,Small states,Small states,S1,NaN,NaN,NaN,S1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
229,TEA,East Asia & Pacific (IDA & IBRD),East Asia & Pacific (IDA & IBRD),East Asia & Pacific (IDA & IBRD),T4,NaN,NaN,NaN,T4,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
230,TEC,Europe & Central Asia (IDA & IBRD),Europe & Central Asia (IDA & IBRD),Europe & Central Asia (IDA & IBRD),T7,NaN,NaN,NaN,T7,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
235,TLA,Latin America & Caribbean (IDA & IBRD),Latin America & Caribbean (IDA & IBRD),Latin America & Caribbean (IDA & IBRD),T2,NaN,NaN,NaN,T2,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
237,TMN,Middle East & North Africa (IDA & IBRD),Middle East & North Africa (IDA & IBRD),Middle East & North Africa (IDA & IBRD),T3,NaN,NaN,NaN,T3,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
239,TSA,South Asia (IDA & IBRD),South Asia (IDA & IBRD),South Asia (IDA & IBRD),T5,NaN,NaN,NaN,T5,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
240,TSS,Sub-Saharan Africa (IDA & IBRD),Sub-Saharan Africa (IDA & IBRD),Sub-Saharan Africa (IDA & IBRD),T6,NaN,NaN,NaN,T6,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
248,UMC,Upper middle income,Upper middle income,Upper middle income,XT,NaN,NaN,NaN,XT,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
253,VEN,Venezuela,"Venezuela, RB",Rep√∫blica Bolivariana de Venezuela,VE,Venezuelan bolivar fuerte,Latin America & Caribbean,NaN,VE,1997,...,NaN,NaN,Enhanced General Data Dissemination System (e-...,2011,"Multiple Indicator Cluster Survey, 2000","Integrated household survey (IHS), 2015",NaN,2008,1998.0,2013.0
258,WLD,World,World,World,1W,NaN,NaN,NaN,1W,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
266,VEN,Venezuela,"Venezuela, RB",Rep√∫blica Bolivariana de Venezuela,VE,Venezuelan bolivar fuerte,Latin America & Caribbean,NaN,VE,1997,...,NaN,NaN,Enhanced General Data Dissemination System (e-...,2011,"Multiple Indicator Cluster Survey, 2000","Integrated household survey (IHS), 2015",NaN,2008,1998.0,2013.0

In [13]:
missing_rows = df[df['WB-2 code'].isnull()]
missing_rows

,Country Code,Short Name,Table Name,Long Name,2-alpha code,Currency Unit,Region,Income Group,WB-2 code,National accounts base year,...,System of trade,Government Accounting concept,IMF data dissemination standard,Latest population census,Latest household survey,Source of most recent Income and expenditure data,Vital registration complete,Latest agricultural census,Latest industrial data,Latest trade data
170,NAM,Namibia,Namibia,Republic of Namibia,NaN,Namibian dollar,Sub-Saharan Africa,Upper middle income,NaN,2015,...,General trade system,Budgetary central government,Enhanced General Data Dissemination System (e-...,2011,"Demographic and Health Survey, 2013","Expenditure survey/budget survey (ES/BS), 2015",NaN,2013-2014,2013.0,2018.0

In [14]:
df['Region'].mode()

0    Europe & Central Asia
Name: Region, dtype: object

In [15]:
df['Income Group'].mode()

0    High income
Name: Income Group, dtype: object

In [16]:
df['2-alpha code'] = df['2-alpha code'].fillna('Unknown')
df['Currency Unit'] = df['Currency Unit'].fillna(df['Currency Unit'].mode()[0])
df['Region'] = df['Region'].fillna(df['Region'].mode()[0])
df['Income Group'] = df['Income Group'].fillna(df['Income Group'].mode()[0])
df['WB-2 code']=df['WB-2 code'].fillna('Unknown')

In [17]:
df['SNA price valuation'] = df['SNA price valuation'].fillna('Unknown')
df['Lending category'] = df['Lending category'].fillna('Unknown')
df['Other groups'] = df['Other groups'].fillna('Unknown')
df['System of National Accounts'] = df['System of National Accounts'].fillna('Unknown')

In [18]:
df.drop(columns=['Alternative conversion factor','PPP survey year'],inplace=True)

In [19]:
df['Balance of Payments Manual in use'] = df['Balance of Payments Manual in use'].fillna('Unknown')
df['External debt Reporting status'] = df['External debt Reporting status'].fillna('Unknown')
df['System of trade'] = df['System of trade'].fillna(df['System of trade'].mode()[0])
df['Government Accounting concept'] = df['Government Accounting concept'].fillna(df['Government Accounting concept'].mode()[0])
df['IMF data dissemination standard'] = df['IMF data dissemination standard'].fillna(df['IMF data dissemination standard'].mode()[0])

In [20]:
df['National accounts base year']=df['National accounts base year'].fillna(method='ffill')
df['National accounts reference year']=df['National accounts reference year'].fillna(method='bfill')

<ipython-input-20-2fafdeeb32e6>:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['National accounts base year']=df['National accounts base year'].fillna(method='ffill')
<ipython-input-20-2fafdeeb32e6>:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['National accounts reference year']=df['National accounts reference year'].fillna(method='bfill')

In [21]:
missing_rows = df[df['National accounts base year'].isnull()]
missing_rows

Empty DataFrame
Columns: [Country Code, Short Name, Table Name, Long Name, 2-alpha code, Currency Unit, Region, Income Group, WB-2 code, National accounts base year, National accounts reference year, SNA price valuation, Lending category, Other groups, System of National Accounts, Balance of Payments Manual in use, External debt Reporting status, System of trade, Government Accounting concept, IMF data dissemination standard, Latest population census, Latest household survey, Source of most recent Income and expenditure data, Vital registration complete, Latest agricultural census, Latest industrial data, Latest trade data]
Index: []

[0 rows x 27 columns]

In [22]:
df['Latest population census'] = df['Latest population census'].fillna(df['Latest population census'].mode()[0])
df['Latest household survey'] = df['Latest household survey'].fillna('Unknown')
df['Source of most recent Income and expenditure data'] = df['Source of most recent Income and expenditure data'].fillna('Unknown')
df['Vital registration complete'] = df['Vital registration complete'].fillna('Unknown')
df['Latest agricultural census'] = df['Latest agricultural census'].fillna(df['Latest agricultural census'].mode()[0])

In [23]:
df['Latest industrial data'] = df['Latest industrial data'].fillna(df['Latest industrial data'].median())
df['Latest trade data'] = df['Latest trade data'].fillna(df['Latest trade data'].median())

In [24]:
df['Balance of Payments Manual in use'] = df['Balance of Payments Manual in use'].fillna('Unknown')

In [25]:
df.isnull().sum()

Country Code                                         0
Short Name                                           0
Table Name                                           0
Long Name                                            0
2-alpha code                                         0
Currency Unit                                        0
Region                                               0
Income Group                                         0
WB-2 code                                            0
National accounts base year                          0
National accounts reference year                     1
SNA price valuation                                  0
Lending category                                     0
Other groups                                         0
System of National Accounts                          0
Balance of Payments Manual in use                    0
External debt Reporting status                       0
System of trade                                      0
Government Accounting concept                        0
IMF data dissemination standard                      0
Latest population census                             0
Latest household survey                              0
Source of most recent Income and expenditure data    0
Vital registration complete                          0
Latest agricultural census                           0
Latest industrial data                               0
Latest trade data                                    0
dtype: int64

### identify duplicates

In [26]:
# 1.4 Identify the duplicate values in the dataset.
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
262    False
263    False
264    False
265     True
266    False
Length: 267, dtype: bool

In [27]:
df.duplicated().sum()

1

In [28]:
# 1.5 Keep one first duplicate value and one last duplicate value.
df1=df.drop_duplicates(keep='first')
df1

,Country Code,Short Name,Table Name,Long Name,2-alpha code,Currency Unit,Region,Income Group,WB-2 code,National accounts base year,...,System of trade,Government Accounting concept,IMF data dissemination standard,Latest population census,Latest household survey,Source of most recent Income and expenditure data,Vital registration complete,Latest agricultural census,Latest industrial data,Latest trade data
0,ABW,Aruba,Aruba,Aruba,AW,Aruban florin,Latin America & Caribbean,High income,AW,2013,...,General trade system,Consolidated central government,Enhanced General Data Dissemination System (e-...,2020 (expected),Unknown,Unknown,Yes,2010,2012.0,2018.0
1,AFE,Africa Eastern and Southern,Africa Eastern and Southern,Africa Eastern and Southern,ZH,Euro,Europe & Central Asia,High income,ZH,2013,...,General trade system,Consolidated central government,Enhanced General Data Dissemination System (e-...,2020 (expected),Unknown,Unknown,Unknown,2010,2012.0,2018.0
2,AFG,Afghanistan,Afghanistan,Islamic State of Afghanistan,AF,Afghan afghani,South Asia,Low income,AF,2016,...,General trade system,Consolidated central government,Enhanced General Data Dissemination System (e-...,1979,"Demographic and Health Survey, 2015","Integrated household survey (IHS), 2016/17",Unknown,2010,2012.0,2018.0
3,AFW,Africa Western and Central,Africa Western and Central,Africa Western and Central,ZI,Euro,Europe & Central Asia,High income,ZI,2016,...,General trade system,Consolidated central government,Enhanced General Data Dissemination System (e-...,2020 (expected),Unknown,Unknown,Unknown,2010,2012.0,2018.0
4,AGO,Angola,Angola,People's Republic of Angola,AO,Angolan kwanza,Sub-Saharan Africa,Lower middle income,AO,2002,...,General trade system,Budgetary central government,Enhanced General Data Dissemination System (e-...,2014,"Demographic and Health Survey, 2015/16","Integrated household survey (IHS), 2008/09",Unknown,2010,2012.0,2018.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,YEM,Yemen,"Yemen, Rep.",Republic of Yemen,YE,Yemeni rial,Middle East & North Africa,Low income,RY,1990,...,Special trade system,Consolidated central government,Enhanced General Data Dissemination System (e-...,2004,"Demographic and Health Survey, 2013","Expenditure survey/budget survey (ES/BS), 2014",Unknown,2010,2012.0,2015.0
262,ZAF,South Africa,South Africa,Republic of South Africa,ZA,South African rand,Sub-Saharan Africa,Upper middle income,ZA,2015,...,General trade system,Consolidated central government,Special Data Dissemination Standard (SDDS),2011,"Demographic and Health Survey, 2016","Expenditure survey/budget survey (ES/BS), 2014/15",Unknown,2007,2010.0,2018.0
263,ZMB,Zambia,Zambia,Republic of Zambia,ZM,New Zambian kwacha,Sub-Saharan Africa,Lower middle income,ZM,2010,...,General trade system,Budgetary central government,Enhanced General Data Dissemination System (e-...,2020 (expected),"Demographic and Health Survey, 2018","Integrated household survey (IHS), 2015",Unknown,2010,1994.0,2018.0
264,ZWE,Zimbabwe,Zimbabwe,Republic of Zimbabwe,ZW,Zimbabwean Dollar,Sub-Saharan Africa,Lower middle income,ZW,2019,...,General trade system,Budgetary central government,Enhanced General Data Dissemination System (e-...,2012,"Multiple Indicator Cluster Survey, 2019","Integrated household survey (IHS), 2011/12",Unknown,2010,2012.0,2018.0
266,VEN,Venezuela,"Venezuela, RB",Rep√∫blica Bolivariana de Venezuela,VE,Venezuelan bolivar fuerte,Latin America & Caribbean,High income,VE,1997,...,General trade system,Consolidated central government,Enhanced General Data Dissemination System (e-...,2011,"Multiple Indicator Cluster Survey, 2000","Integrated household survey (IHS), 2015",Unknown,2008,1998.0,2013.0

In [29]:
df2=df.drop_duplicates(keep='last')
df2

,Country Code,Short Name,Table Name,Long Name,2-alpha code,Currency Unit,Region,Income Group,WB-2 code,National accounts base year,...,System of trade,Government Accounting concept,IMF data dissemination standard,Latest population census,Latest household survey,Source of most recent Income and expenditure data,Vital registration complete,Latest agricultural census,Latest industrial data,Latest trade data
0,ABW,Aruba,Aruba,Aruba,AW,Aruban florin,Latin America & Caribbean,High income,AW,2013,...,General trade system,Consolidated central government,Enhanced General Data Dissemination System (e-...,2020 (expected),Unknown,Unknown,Yes,2010,2012.0,2018.0
1,AFE,Africa Eastern and Southern,Africa Eastern and Southern,Africa Eastern and Southern,ZH,Euro,Europe & Central Asia,High income,ZH,2013,...,General trade system,Consolidated central government,Enhanced General Data Dissemination System (e-...,2020 (expected),Unknown,Unknown,Unknown,2010,2012.0,2018.0
2,AFG,Afghanistan,Afghanistan,Islamic State of Afghanistan,AF,Afghan afghani,South Asia,Low income,AF,2016,...,General trade system,Consolidated central government,Enhanced General Data Dissemination System (e-...,1979,"Demographic and Health Survey, 2015","Integrated household survey (IHS), 2016/17",Unknown,2010,2012.0,2018.0
3,AFW,Africa Western and Central,Africa Western and Central,Africa Western and Central,ZI,Euro,Europe & Central Asia,High income,ZI,2016,...,General trade system,Consolidated central government,Enhanced General Data Dissemination System (e-...,2020 (expected),Unknown,Unknown,Unknown,2010,2012.0,2018.0
4,AGO,Angola,Angola,People's Republic of Angola,AO,Angolan kwanza,Sub-Saharan Africa,Lower middle income,AO,2002,...,General trade system,Budgetary central government,Enhanced General Data Dissemination System (e-...,2014,"Demographic and Health Survey, 2015/16","Integrated household survey (IHS), 2008/09",Unknown,2010,2012.0,2018.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
262,ZAF,South Africa,South Africa,Republic of South Africa,ZA,South African rand,Sub-Saharan Africa,Upper middle income,ZA,2015,...,General trade system,Consolidated central government,Special Data Dissemination Standard (SDDS),2011,"Demographic and Health Survey, 2016","Expenditure survey/budget survey (ES/BS), 2014/15",Unknown,2007,2010.0,2018.0
263,ZMB,Zambia,Zambia,Republic of Zambia,ZM,New Zambian kwacha,Sub-Saharan Africa,Lower middle income,ZM,2010,...,General trade system,Budgetary central government,Enhanced General Data Dissemination System (e-...,2020 (expected),"Demographic and Health Survey, 2018","Integrated household survey (IHS), 2015",Unknown,2010,1994.0,2018.0
264,ZWE,Zimbabwe,Zimbabwe,Republic of Zimbabwe,ZW,Zimbabwean Dollar,Sub-Saharan Africa,Lower middle income,ZW,2019,...,General trade system,Budgetary central government,Enhanced General Data Dissemination System (e-...,2012,"Multiple Indicator Cluster Survey, 2019","Integrated household survey (IHS), 2011/12",Unknown,2010,2012.0,2018.0
265,AUS,Australia,Australia,Commonwealth of Australia,AU,Australian dollar,East Asia & Pacific,High income,AU,Original chained constant price data are resca...,...,General trade system,Consolidated central government,Special Data Dissemination Standard (SDDS),2016,Unknown,"Expenditure survey/budget survey (ES/BS), 2010",Yes,2015-2016,2013.0,2018.0
266,VEN,Venezuela,"Venezuela, RB",Rep√∫blica Bolivariana de Venezuela,VE,Venezuelan bolivar fuerte,Latin America & Caribbean,High income,VE,1997,...,General trade system,Consolidated central government,Enhanced General Data Dissemination System (e-...,2011,"Multiple Indicator Cluster Survey, 2000","Integrated household survey (IHS), 2015",Unknown,2008,1998.0,2013.0

In [30]:
df['System of trade'].unique()

array(['General trade system', 'Special trade system'], dtype=object)

In [31]:
# 1.6 Convert the categorical features into numerical features using the map function for columns ‚Äì System of trade, Government Accounting concept, Vital registration complete
df['System of trade'] = df['System of trade'].map({'General trade system': 1,'Special trade system': 2})

In [32]:
df['Government Accounting concept'].unique()

array(['Consolidated central government', 'Budgetary central government'],
      dtype=object)

In [33]:
df['Government Accounting concept'] = df['Government Accounting concept'].map({'Consolidated central government': 1,'Budgetary central government': 2})

In [34]:
df['Government Accounting concept'].unique()

array([1, 2])

In [35]:
df['Vital registration complete'].unique()

array(['Yes', 'Unknown',
       'Yes. Vital registration for Guernsey and Jersey.'], dtype=object)

In [36]:
df['Vital registration complete'] = df['Vital registration complete'].map({'Yes': 1,'Unknown': 2,'Yes. Vital registration for Guernsey and Jersey.':3})

In [37]:
df['Vital registration complete'].unique()

array([1, 2, 3])

In [38]:
# 1.7 Convert the categorical features into numerical features using dummy variables for columns ‚Äì Region, Income Group
df_region=pd.get_dummies(df['Region'],dtype=int,prefix='Region_category')
df_region

,Region_category_East Asia & Pacific,Region_category_Europe & Central Asia,Region_category_Latin America & Caribbean,Region_category_Middle East & North Africa,Region_category_North America,Region_category_South Asia,Region_category_Sub-Saharan Africa
0,0,0,1,0,0,0,0
1,0,1,0,0,0,0,0
2,0,0,0,0,0,1,0
3,0,1,0,0,0,0,0
4,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...
262,0,0,0,0,0,0,1
263,0,0,0,0,0,0,1
264,0,0,0,0,0,0,1
265,1,0,0,0,0,0,0
266,0,0,1,0,0,0,0

In [39]:
df_income=pd.get_dummies(df['Income Group'],dtype=int,prefix='Income Group')
df_income

,Income Group_High income,Income Group_Low income,Income Group_Lower middle income,Income Group_Upper middle income
0,1,0,0,0
1,1,0,0,0
2,0,1,0,0
3,1,0,0,0
4,0,0,1,0
...,...,...,...,...
262,0,0,0,1
263,0,0,1,0
264,0,0,1,0
265,1,0,0,0
266,1,0,0,0

In [40]:
# 1.8 Rename the columns with the prefix of the original column for dummy columns. i.e. Region_ South Asia, Income Group_ High income etc.
df.rename(columns={'Region_South Asia': 'Region_South_Asia', 'Income Group_High income': 'Income_Group_High_income'})

,Country Code,Short Name,Table Name,Long Name,2-alpha code,Currency Unit,Region,Income Group,WB-2 code,National accounts base year,...,System of trade,Government Accounting concept,IMF data dissemination standard,Latest population census,Latest household survey,Source of most recent Income and expenditure data,Vital registration complete,Latest agricultural census,Latest industrial data,Latest trade data
0,ABW,Aruba,Aruba,Aruba,AW,Aruban florin,Latin America & Caribbean,High income,AW,2013,...,1,1,Enhanced General Data Dissemination System (e-...,2020 (expected),Unknown,Unknown,1,2010,2012.0,2018.0
1,AFE,Africa Eastern and Southern,Africa Eastern and Southern,Africa Eastern and Southern,ZH,Euro,Europe & Central Asia,High income,ZH,2013,...,1,1,Enhanced General Data Dissemination System (e-...,2020 (expected),Unknown,Unknown,2,2010,2012.0,2018.0
2,AFG,Afghanistan,Afghanistan,Islamic State of Afghanistan,AF,Afghan afghani,South Asia,Low income,AF,2016,...,1,1,Enhanced General Data Dissemination System (e-...,1979,"Demographic and Health Survey, 2015","Integrated household survey (IHS), 2016/17",2,2010,2012.0,2018.0
3,AFW,Africa Western and Central,Africa Western and Central,Africa Western and Central,ZI,Euro,Europe & Central Asia,High income,ZI,2016,...,1,1,Enhanced General Data Dissemination System (e-...,2020 (expected),Unknown,Unknown,2,2010,2012.0,2018.0
4,AGO,Angola,Angola,People's Republic of Angola,AO,Angolan kwanza,Sub-Saharan Africa,Lower middle income,AO,2002,...,1,2,Enhanced General Data Dissemination System (e-...,2014,"Demographic and Health Survey, 2015/16","Integrated household survey (IHS), 2008/09",2,2010,2012.0,2018.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
262,ZAF,South Africa,South Africa,Republic of South Africa,ZA,South African rand,Sub-Saharan Africa,Upper middle income,ZA,2015,...,1,1,Special Data Dissemination Standard (SDDS),2011,"Demographic and Health Survey, 2016","Expenditure survey/budget survey (ES/BS), 2014/15",2,2007,2010.0,2018.0
263,ZMB,Zambia,Zambia,Republic of Zambia,ZM,New Zambian kwacha,Sub-Saharan Africa,Lower middle income,ZM,2010,...,1,2,Enhanced General Data Dissemination System (e-...,2020 (expected),"Demographic and Health Survey, 2018","Integrated household survey (IHS), 2015",2,2010,1994.0,2018.0
264,ZWE,Zimbabwe,Zimbabwe,Republic of Zimbabwe,ZW,Zimbabwean Dollar,Sub-Saharan Africa,Lower middle income,ZW,2019,...,1,2,Enhanced General Data Dissemination System (e-...,2012,"Multiple Indicator Cluster Survey, 2019","Integrated household survey (IHS), 2011/12",2,2010,2012.0,2018.0
265,AUS,Australia,Australia,Commonwealth of Australia,AU,Australian dollar,East Asia & Pacific,High income,AU,Original chained constant price data are resca...,...,1,1,Special Data Dissemination Standard (SDDS),2016,Unknown,"Expenditure survey/budget survey (ES/BS), 2010",1,2015-2016,2013.0,2018.0
266,VEN,Venezuela,"Venezuela, RB",Rep√∫blica Bolivariana de Venezuela,VE,Venezuelan bolivar fuerte,Latin America & Caribbean,High income,VE,1997,...,1,1,Enhanced General Data Dissemination System (e-...,2011,"Multiple Indicator Cluster Survey, 2000","Integrated household survey (IHS), 2015",2,2008,1998.0,2013.0

In [41]:
df.columns

Index(['Country Code', 'Short Name', 'Table Name', 'Long Name', '2-alpha code',
       'Currency Unit', 'Region', 'Income Group', 'WB-2 code',
       'National accounts base year', 'National accounts reference year',
       'SNA price valuation', 'Lending category', 'Other groups',
       'System of National Accounts', 'Balance of Payments Manual in use',
       'External debt Reporting status', 'System of trade',
       'Government Accounting concept', 'IMF data dissemination standard',
       'Latest population census', 'Latest household survey',
       'Source of most recent Income and expenditure data',
       'Vital registration complete', 'Latest agricultural census',
       'Latest industrial data', 'Latest trade data'],
      dtype='object')